# Generated by Django 4.1 on 2022-12-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="assignee",
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="epic",
            name="assignee",
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name="epic",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
