# Generated by Django 4.1 on 2022-12-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_epic_cards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
